version: '3'
services:
    api:
        container_name: api
        build: ./api/
        image: ${regAddr}/api:${BUILD_NUMBER}
        env_file:
            - ./api/env
        ports: 
            - '8080:5001'
        networks:
            - fask_app_main-net

    redis:
        container_name: redis
        image: redis
        networks:
            - fask_app_main-net
                


    app:
        container_name: app
        build: ./app/
        image: ${regAddr}/app:${BUILD_NUMBER}
        ports:
            - '80:5000'
        networks:
            - fask_app_main-net

    db:
        container_name: db
        build: ./db/
        image: ${regAddr}/db:${BUILD_NUMBER}
        networks:
            - fask_app_main-net
        volumes:
            - mysqldb:/var/lib/mysql



networks:
    main-net:
        driver: bridge

volumes:
    mysqldb:
