- hosts: all
  become: yes
  remote_user: ec2-user
  become_user: root
  tasks:
    - name: Install Dependencies for nexus
      yum:
        name: "{{ package }} "
        state: present
      vars:
        package:
        - net-tools
        - java-1.8.0-openjdk
        - java-1.8.0-openjdk-devel

    - name: install epel 
      shell: "amazon-linux-extras install epel -y"


    - name: Nexus repo
      get_url:
        url: http://download.sonatype.com/nexus/3/latest-unix.tar.gz
        dest: /tmp/nexus.tar.gz
   
    - name: nexus user add
      user:
        name: nexus
        state: present
    
    
#    - name: create nexus dir
#      file:
#        path: /opt/nexus
#        state: directory
#        owner: nexus
#        group: nexus

    - name: create nexus dir
      file:
        path: /data/nexus-data
        state: directory
        owner: nexus
        group: nexus


    - name: extract nexus
      unarchive:
        src: /tmp/nexus.tar.gz
        dest: /opt
        remote_src: true

    - name: rename nuxus dir
      command: mv /opt/nexus-3.38.1-01 /opt/nexus

    - name: nexus dir permissins
      file:
        path: /opt/nexus
        state: directory
        owner: nexus
        group: nexus
        recurse: yes

    - name: setting env
      shell: echo "export JAVA_HOME=$(dirname $(dirname $(readlink $(readlink $(which javac)))))" >> /etc/bashrc

    - name: setting env
      command: echo "export NEXUS_HOME=/opt/nexus" >> /etc/bashrc

    - name: update current shell env
      shell: source /etc/bashrc
      args:
        executable: /bin/bash

#    - name: Nexus directory permissions
#      file:
#        path: /opt/nexus
#        state: directory
#        recursive: yes
#        owner: nexus

#    - name: copy source to nexus
#      copy:
#        src: /opt/nexus/nexus-3.38.1-01
#        dest: /opt/
#        remote_src: true
#    - name: rename nuxus dir
#      command: mv /opt/nexus-3.38.1-01 /opt/nexus

    - name: copy configs
      copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: nexus
        group: nexus
      with_items:
        - { src: ./nexus.vmoptions, dest: /opt/nexus/bin/nexus.vmoptions }
        - { src: ./nexus.service, dest: /etc/systemd/system/nexus.service }
        - { src: ./nexus.rc, dest: /opt/nexus/bin/nexus.rc }

    - name: change default password
      command: echo admin123 > /data/nexus-data/nexus3/admin.password

    - name: reload daemon
      shell: "systemctl daemon-reload"

    - name: start Nexus
      service:
        name: nexus
        state: started
        enabled: yes
 
