---
- hosts: all
  become: yes
  remote_user: ec2-user
  become_user: root
  tasks:
    - name: install dependencies
      yum:
        name: "{{ package }} "
      vars:
        package:
        - wget
        - java-1.8.0-openjdk-devel
        - git
    - name: check if docker exist
      stat: path=/usr/bin/docker
      register: service_status

#    - name: Install Docker
#      ansible.builtin.shell: cd ~ && curl -fsSL https://get.docker.com -o get-docker.sh && sudo sh get-docker.sh
#      when: service.state.docker is not defined
#      when: not service_status.stat.exists

    - name: Install Docker on amzn
      yum:
        name: docker
        state: present

    - name: start docker service
      service:
        name: docker
        state: started
        enabled: yes
      
    - name: install docker-compose
      get_url:
        url: "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-Linux-x86_64"
        dest: /usr/local/bin/docker-compose
        mode: '0777'

    - name: change docker-comppose permisisons
      command: chmod 755 /usr/local/bin/docker-compose     

#    - name: create jenkins home directory
#      file:
#        path: /var/lib/jenkins
#        state: directory
# IP=$(ip addr show eth0 | grep 'inet\b' | awk '{print $2}' | cut -d/ -f1) &&     
    - name: init docker swarm
      command: docker swarm init --advertise-addr {{ inventory_hostname }}
#    - name: Init a new swarm with default parameters
#      docker_swarm:
#        state: present      
        
    - name: add jekins user
      user:
        name: jenkins
        password: 123@qwer
        home: /var/lib/jenkins
        state: present
        createhome: yes

    - name: add to sudoers
      copy:
        dest: /etc/sudoers.d/jenkins
        content: "jenkins ALL=(ALL) NOPASSWD: ALL"
    - name: make direcotry
      file:
        path: /var/lib/jenkins/.ssh
        state: directory
        mode: 0755
    - name: create empty file
      file:
        path: /var/lib/jenkins/.ssh/authorized_keys
        state: touch
        mode: 0755
    - name: put pubkey
      lineinfile:
        path: /var/lib/jenkins/.ssh/authorized_keys
        line: "{{ lookup('file', '/root/.ssh/id_rsa.pub') }}"

    - name: copy daeon.jsion
      copy:
        src: ./daemon.json
        dest: /etc/docker/daemon.json

#    - name: change regitsry address
#      replace:
#        path: /etc/docker/daemon.json
#        regexp: 'c4df90f5fc3c.mylabserver.com'
#        replace: "{{ nexus_address }}"

#    - name: change regitsry address
#      replace:
#        path: /etc/docker/daemon.json
#        regexp: 'fluentdhost'
#        replace: "{{ logging_address }}"


    - name: restart systemd
      command: systemctl daemon-reload

    - name: restart docker
      command: systemctl restart docker

    - name: chmod docker.sock
      file: path=/var/run/docker.sock mode=666

