---
- hosts: all
  become: yes
  remote_user: ansible
  become_user: root
  tasks:
    - name: install dependencies
      yum:
        name: "{{ package }} "
      vars:
        package:
        - wget
        - java-1.8.0-openjdk-devel
        - git
    - name: check if docker exist
      stat: path=/usr/bin/docker
      register: service_status

#    - name: Install Docker
#      ansible.builtin.shell: cd ~ && curl -fsSL https://get.docker.com -o get-docker.sh && sudo sh get-docker.sh
#      when: service.state.docker is not defined
#      when: not service_status.stat.exists

    - name: Install Docker on amzn
      yum:
        name: docker
        state: present

    - name: start docker service
      service:
        name: docker
        state: started
        enabled: yes
      
    - name: install docker-compose
      get_url:
        url: "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-Linux-x86_64"
        dest: /usr/local/bin/docker-compose
        mode: '0777'

    - name: change docker-comppose permisisons
      command: chmod 755 /usr/local/bin/docker-compose     

#    - name: create jenkins home directory
#      file:
#        path: /var/lib/jenkins
#        state: directory
       
    - name: add jekins user
      user:
        name: jenkins
        password: 123@qwer
        home: /var/lib/jenkins
        state: present
        createhome: yes

    - name: add to sudoers
      copy:
        dest: /etc/sudoers.d/jenkins
        content: "jenkins ALL=(ALL) NOPASSWD: ALL"
    - name: make direcotry
      file:
        path: /var/lib/jenkins/.ssh
        state: directory
        mode: 0755
    - name: create empty file
      file:
        path: /var/lib/jenkins/.ssh/authorized_keys
        state: touch
        mode: 0755
#    - name: put pubkey
#      lineinfile:
#        path: /var/lib/jenkins/.ssh/authorized_keys
#        line:  "{{ lookup(‘file’, ‘/root/.ssh/id_rsa.pub’) }}"
#    - name: create daemon.json
#      file:
#        path: /etc/docker/daemon.json
#        state: file
#        mode: 0755

#    - name: config docker for insecure registry
#      lineinfile:
#        path: /etc/docker/daemon.json
#        content: "{{ lookup('file', './daemon.json')}}"
#        state: present

    - name: copy daeon.jsion
      copy:
        src: ./daemon.json
        dest: /etc/docker/daemon.json

    - name: restart systemd
      command: systemctl daemon-reload

    - name: restart docker
      command: systemctl restart docker
