global:
  resolve_timeout: 1m
  slack_api_url: 'https://hooks.slack.com/services/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'
 
route:
  receiver: 'slack-notifications'
 
receivers:
- name: 'slack-notifications'
  slack_configs:
  - channel: '#flask-app'
    send_resolved: true
    text: 'HEY HEY HEY'
