name: test commet
on:
  issue_comment:                                     
    types: [created, edited, deleted]

jobs:
  test-commit:
    runs-on: ubuntu-latest
    if: contains(github.event.comment.body, '/support')
    steps:
      - name: Run tests
        run: echo running tests
