name: Run Tests

on:
  pull_request:
    branches:
      - master

jobs:
  main_trigger:
    name:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    if: "contains(github.event.comment.body, 'hossein')"
    steps:
      - name: Run tests
        run: echo running tests
