name: test commet
on:
  pull_request:
    branch: master

jobs:
  test-commit:
    runs-on: ubuntu-latest
    if: github.event.review.state == 'approved'
    steps:
      - name: Run tests
        run: echo running tests
