name: test commet
on:
  pull_request:
    types: [opened]
  issue_comment:
    types: [created]

jobs:
  like-pizza:
    runs-on: ubuntu-latest
    if: ${{ github.event.issue.pull_request && github.event.comment.body == 'hossein'}}
    steps:
      - name: Run tests
        run: echo running tests
