name: test commet
on:
  pull_request:
    branch: master

jobs:
  test-commit:
    runs-on: ubuntu-latest
    if: contains(github.event.comment.body, '/support')
    steps:
      - name: Run tests
        run: echo running tests
