name: Like pizza

on:
  issue_comment:
    types:
      - created

jobs:
  like-pizza:
    runs-on: ubuntu-latest
    if: ${{ github.event.comment.body == 'hossein'}}
    steps:
      - name: Run tests
        run: echo running tests
